config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get "search" => "searches#search"
  get "search_result" => "searches#search_result"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  
  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
    @word = params[:word]
    render :search_result
  end
  
  def search_result
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search_result.html.erb
<table class="table table-hover table-inverse">
  <% if @range == "User" %>
    <% if @users.exists? %>
      <thead>
        <h1>Users search for "<%= @word %>"</h1>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image, size:'50x50' %></td>
            <td><%= link_to user.name,user_path(user.id) %></td>
            <td><%= user.introduction %></td>
          </tr>
        <% end %>
      </tbody>
    <% else %>
      <p>条件に合ったユーザーはいませんでした。</p>
    <% end %>
  <% else %>
    <% if @books.exists? %>
    <thead>
      <h1>Books search for "<%= @word %>"</h1>
      <tr>
        <th>Image</th>
        <th>Title</th>
        <th colspan="3">Opinion</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= image_tag book.user.get_profile_image, size:'50x50' %></td>
          <td><%= link_to book.title,book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
    <% else %>
      <p>条件に合った本はありませんでした。</p>
    <% end %>
  <% end %>
</table> 